services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=3a7c4f8d2e1b5a9c7d8e2f1b5a3c4d9e
      - N(N_SECURE_COOKIE=false
    volumes:
      - ~/Documents/documentation_project/n8n-data:/home/node/.n8n
      - ~/Documents/documentation_project/documentation:/repo

  docs-server:
    image: halverneus/static-file-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FOLDER=/var/www/html
    volumes:
      - ~/Documents/documentation_project/documentation/doc:/var/www/html
